/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tutankhamun_gold_mask.glb --transform 
Files: tutankhamun_gold_mask.glb [5.69MB] > H:\coding\portofolio\public\models\tutankhamun_gold_mask-transformed.glb [494.68KB] (91%)
Author: amirfiala1 (https://sketchfab.com/amirfiala1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tutankhamun-gold-mask-992c57047cdf4412b970ad798d5ad0c9
Title: Tutankhamun Gold Mask
*/

import { useGLTF } from "@react-three/drei";

export function Tut(props) {
  const { nodes, materials } = useGLTF(
    "/models/tutankhamun_gold_mask-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Default_150150150_Default_150150150_0.geometry}
        material={materials.Default_150150150}
        position={[-122.626, -1.19, 35.504]}
        rotation={[-1.626, 0.008, 0.021]}
      />
      <mesh
        geometry={nodes.tut_mask_back_tut_mask_back_0.geometry}
        material={materials.tut_mask_back}
        position={[-122.626, -1.19, 35.504]}
        rotation={[-1.626, 0.008, 0.021]}
      />
      <mesh
        geometry={nodes.tutmask_bearded_tutmask_bearded_0.geometry}
        material={materials.tutmask_bearded}
        position={[-122.626, -1.19, 35.504]}
        rotation={[-1.626, 0.008, 0.021]}
      />
      <mesh
        geometry={nodes.tutmask_bigears_tutmask_bigears_0.geometry}
        material={materials.tutmask_bigears}
        position={[-122.626, -1.19, 35.504]}
        rotation={[-1.626, 0.008, 0.021]}
      />
      <mesh
        geometry={
          nodes
            .tutmask_front_and_side_no_beard_tutmask_front_and_side_no_beard_0
            .geometry
        }
        material={materials.tutmask_front_and_side_no_beard}
        position={[-122.626, -1.19, 35.504]}
        rotation={[-1.626, 0.008, 0.021]}
      />
      <mesh
        geometry={
          nodes
            .tutmask_front_no_beard_ears_or_snake_tutmask_front_no_beard_ears_or_snake_0
            .geometry
        }
        material={materials.tutmask_front_no_beard_ears_or_snake}
        position={[-122.626, -1.19, 35.504]}
        rotation={[-1.626, 0.008, 0.021]}
      />
    </group>
  );
}

useGLTF.preload("/models/tutankhamun_gold_mask-transformed.glb");
